#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */


    while(1)
    {
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_02, BSP_IO_LEVEL_HIGH);
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_03, BSP_IO_LEVEL_HIGH);
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_04, BSP_IO_LEVEL_HIGH);
//        R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
//
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_02, BSP_IO_LEVEL_LOW);
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_03, BSP_IO_LEVEL_LOW);
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_04, BSP_IO_LEVEL_LOW);
//        R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);

        /*向端口BSP_IO_PORT_01的第3写入1，4位写入0
         * BSP_IO_PORT_01 是指定的端口。
         * 0x0008 是要写入的值，其中位3设置为1（0x0008 在二进制表示中为 0000 0000 0000 1000）。
         * 0x0018 是掩码，表示要更新的位是3位和第4位（0x0018 在二进制表示中为 0000 0000 0001 1000）。
         */
        R_IOPORT_PortWrite(&g_ioport_ctrl, BSP_IO_PORT_01, 0x0008, 0x0018);
        R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
        /*向端口BSP_IO_PORT_09的第13写入0，14位写入1
         * BSP_IO_PORT_01 是指定的端口。
         * 0x0010 是要写入的值，其中位3设置为1（0x0010 在二进制表示中为 0000 0000 0001 0000）。
         * 0x0018 是掩码，表示要更新的位是3位和第4位（0x0018 在二进制表示中为 0000 0000 0001 1000）。
         */
        R_IOPORT_PortWrite(&g_ioport_ctrl, BSP_IO_PORT_01, 0x0010, 0x0018);
        R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
    }





#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
